### ISSUE TITLE
MemoryLeak  on Ezthreads_tester (TestForceKill function)

### ISSUE THREAD

**Issue by richiejang** [mr-highball/ezthreads#3]
Hello mr-highball, 

I tried to test your good lib and found the memory-leak.
I tested the library on Lazarus 2.0.4 / FPC 3.2.0

Thank you for such nice Lib.
Best Regards,
Richie.

**Comment by mr-highball** [comment]
Hello @richiejang, first of all, thank you for trying out my library. As for the memory leak, could you describe what makes you think there is one? Did you use heaptrace or something else (found a bug in code, etc...)? If it was heaptrace, I'm actually not surprised on that due that the "force kill" was added for those unique cases where a thread needs to be terminated immediately, but unfortunately this doesn't always allow for the thread to cleanup after itself (so really not recommended to use) because under the hood, abort is called. Some more information can be found about why using this is bad, but like I said before, it was implemented for completeness,
https://forum.lazarus.freepascal.org/index.php?topic=32441.0

**Comment by richiejang** [comment]
Hello Mr-HighBall,

Yes, I used Heaptrace mode in console.
If You are already aware of this issue, No problem for me.
Thank you for the answer.
Best Regards,
Richie.
